name: Build a Raspberry Pi OS image

on:
  push:
    branches:
      - 'gh-actions'

jobs:
  build-raspberrypi-image:
    runs-on: ubuntu-latest

    name: Build a Raspberry Pi OS image
    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        run: echo "CURRENT_DATE=`echo $(date '+%Y-%m-%d')`" >> $GITHUB_ENV

      - name: Build the Raspberry Pi OS image
        run: ./build-docker.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Test build ${{ env.SHORT_SHA }}"
          files: |
            deploy/${{ env.CURRENT_DATE }}-raspberrypi-lite.zip
